// Get all conversations
export const GET_ALL_CONVERSATION_REQUEST = 'GET_ALL_CONVERSATION_REQUEST';
export const GET_ALL_CONVERSATION_SUCCESS = 'GET_ALL_CONVERSATION_SUCCESS';
export const GET_ALL_CONVERSATION_FAILURE = 'GET_ALL_CONVERSATION_FAILURE';

// Get messages by conversation
export const GET_ALL_MESSAGE_REQUEST = 'GET_ALL_MESSAGE_REQUEST';
export const GET_ALL_MESSAGE_SUCCESS = 'GET_ALL_MESSAGE_SUCCESS';
export const GET_ALL_MESSAGE_FAILURE = 'GET_ALL_MESSAGE_FAILURE';

// Send message
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

// Push new message to list message
export const PUSH_NEW_MESSAGE = 'PUSH_NEW_MESSAGE';

// Create conversation
export const CREATE_CONVERSATION_REQUEST = 'CREATE_CONVERSATION_REQUEST';
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS';
export const CREATE_CONVERSATION_FAILURE = 'CREATE_CONVERSATION_FAILURE';

// Create group
export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';

// Add member
export const ADD_MEMBER_REQUEST = 'ADD_MEMBER_REQUEST';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_FAILURE = 'ADD_MEMBER_FAILURE';

// Remove member
export const REMOVE_MEMBER_REQUEST = 'REMOVE_MEMBER_REQUEST';
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS';
export const REMOVE_MEMBER_FAILURE = 'REMOVE_MEMBER_FAILURE';

// Leave group
export const LEAVE_GROUP_REQUEST = 'LEAVE_GROUP_REQUEST';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_FAILURE = 'LEAVE_GROUP_FAILURE';

// Rename group
export const RENAME_GROUP_REQUEST = 'RENAME_GROUP_REQUEST';
export const RENAME_GROUP_SUCCESS = 'RENAME_GROUP_SUCCESS';
export const RENAME_GROUP_FAILURE = 'RENAME_GROUP_FAILURE';

// Save info chat with
export const SAVE_INFO_CHAT_WITH = 'SAVE_INFO_CHAT_WITH';