export const UserConstant = {
    // Login
    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',

    // Register
    REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

    // Logout
    LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST',

    // Get OTP by email
    GET_EMAIL_REQUEST: 'GET_EMAIL_REQUEST',
    GET_EMAIL_SUCCESS: 'GET_EMAIL_SUCCESS',
    GET_EMAIL_FAILURE: 'GET_EMAIL_FAILURE',

    // Check OTP
    CHECK_OTP_REQUEST: 'CHECK_OTP_REQUEST',
    CHECK_OTP_SUCCESS: 'CHECK_OTP_SUCCESS',
    CHECK_OTP_FAILURE: 'CHECK_OTP_FAILURE',

    // Update password
    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',

    // Get new token
    GET_NEW_TOKEN_REQUEST: 'GET_NEW_TOKEN_REQUEST',
    GET_NEW_TOKEN_SUCCESS: 'GET_NEW_TOKEN_SUCCESS',
    GET_NEW_TOKEN_FAILURE: 'GET_NEW_TOKEN_FAILURE',

    // Get user by ID
    GET_USER_BY_ID_REQUEST: 'GET_USER_BY_ID_REQUEST',
    GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
    GET_USER_BY_ID_FAILURE: 'GET_USER_BY_ID_FAILURE',

    // Update avatar
    UPDATE_AVATAR_REQUEST: 'UPDATE_AVATAR_REQUEST',
    UPDATE_AVATAR_SUCCESS: 'UPDATE_AVATAR_SUCCESS',
    UPDATE_AVATAR_FAILURE: 'UPDATE_AVATAR_FAILURE',

    // Search user
    SEARCH_USER_REQUEST: 'SEARCH_USER_REQUEST',
    SEARCH_USER_SUCCESS: 'SEARCH_USER_SUCCESS',
    SEARCH_USER_FAILURE: 'SEARCH_USER_FAILURE',

    // Friends
    GET_ALL_FRIEND_REQUEST: 'GET_ALL_FRIEND_REQUEST',
    GET_ALL_FRIEND_SUCCESS: 'GET_ALL_FRIEND_SUCCESS',
    GET_ALL_FRIEND_FAILURE: 'GET_ALL_FRIEND_FAILURE',
    
    // Friend requests
    GET_ALL_FRIEND_REQUEST_REQUEST: 'GET_ALL_FRIEND_REQUEST_REQUEST',
    GET_ALL_FRIEND_REQUEST_SUCCESS: 'GET_ALL_FRIEND_REQUEST_SUCCESS', 
    GET_ALL_FRIEND_REQUEST_FAILURE: 'GET_ALL_FRIEND_REQUEST_FAILURE',
    
    // Gửi yêu cầu kết bạn
    SEND_FRIEND_REQUEST_REQUEST: 'SEND_FRIEND_REQUEST_REQUEST',
    SEND_FRIEND_REQUEST_SUCCESS: 'SEND_FRIEND_REQUEST_SUCCESS',
    SEND_FRIEND_REQUEST_FAILURE: 'SEND_FRIEND_REQUEST_FAILURE',
    
    // Chấp nhận yêu cầu kết bạn
    ACCEPT_FRIEND_REQUEST_REQUEST: 'ACCEPT_FRIEND_REQUEST_REQUEST',
    ACCEPT_FRIEND_REQUEST_SUCCESS: 'ACCEPT_FRIEND_REQUEST_SUCCESS',
    ACCEPT_FRIEND_REQUEST_FAILURE: 'ACCEPT_FRIEND_REQUEST_FAILURE',
    
    // Từ chối yêu cầu kết bạn
    DECLINE_FRIEND_REQUEST_REQUEST: 'DECLINE_FRIEND_REQUEST_REQUEST',
    DECLINE_FRIEND_REQUEST_SUCCESS: 'DECLINE_FRIEND_REQUEST_SUCCESS',
    DECLINE_FRIEND_REQUEST_FAILURE: 'DECLINE_FRIEND_REQUEST_FAILURE',
    
    // Update user
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    
    // Save email user
    SAVE_EMAIL_USER: 'SAVE_EMAIL_USER',
    
    // Save info user
    SAVE_INFO_USER: 'SAVE_INFO_USER',
    
    // Clear user state
    CLEAR_USER_STATE: 'CLEAR_USER_STATE',
    
    // Update unread messages
    UPDATE_USER_UNREAD_MESSAGES: 'UPDATE_USER_UNREAD_MESSAGES',
    
    // Get all people request
    GET_ALL_PEOPLE_REQUEST_REQUEST: 'GET_ALL_PEOPLE_REQUEST_REQUEST',
    GET_ALL_PEOPLE_REQUEST_SUCCESS: 'GET_ALL_PEOPLE_REQUEST_SUCCESS',
    GET_ALL_PEOPLE_REQUEST_FAILURE: 'GET_ALL_PEOPLE_REQUEST_FAILURE',
    
    // Get User Info
    GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST',
    GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
    GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',
    
    // Change Password
    CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
    
    // Forgot Password
    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
    
    // Reset Password
    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE'
};