export const ChatConstant = {
    GET_ALL_MESSAGE_BY_CONVERSATION_REQUEST: 'GET_ALL_MESSAGE_BY_CONVERSATION_REQUEST',
    GET_ALL_MESSAGE_BY_CONVERSATION_SUCCESS: 'GET_ALL_MESSAGE_BY_CONVERSATION_SUCCESS',
    GET_ALL_MESSAGE_BY_CONVERSATION_FAILURE: 'GET_ALL_MESSAGE_BY_CONVERSATION_FAILURE',

    GET_ALL_CONVERSATION_BY_USER_REQUEST: 'GET_ALL_CONVERSATION_BY_USER_REQUEST',
    GET_ALL_CONVERSATION_BY_USER_SUCCESS: 'GET_ALL_CONVERSATION_BY_USER_SUCCESS',
    GET_ALL_CONVERSATION_BY_USER_FAILURE: 'GET_ALL_CONVERSATION_BY_USER_FAILURE',

    PUSH_NEW_MESSAGE_TO_LIST_MESSAGE: 'PUSH_NEW_MESSAGE_TO_LIST_MESSAGE',
    SAVE_INFO_CHAT_WITH: 'SAVE_INFO_CHAT_WITH',
}